"""Tests for built-in Gerrit message parsing and default CI link extraction."""

from __future__ import annotations

from pathlib import Path

import pytest

from gerrit_workflow_tools.core.ci_links import CiLink, apply_ci_strategy
from gerrit_workflow_tools.core.ci_strategy import (
    clear_ci_strategy_cache,
    default_extract_ci_links,
    extract_ci_links_via_registry,
)
from gerrit_workflow_tools.core.gerrit.service import GerritService
from gerrit_workflow_tools.core.gerrit_change_status import CommitStatusInput
from gerrit_workflow_tools.core.gerrit_message_parsing import (
    jenkins_build_url_from_text,
    jenkins_job_url_to_console,
    parse_change_message,
)
from tests.change_store import ChangeStore
from tests.cli_gerrit_mocks import build_details_by_change_id, stack_rows_mb_to_head


def test_jenkins_job_url_to_console_appends_console() -> None:
    assert (
        jenkins_job_url_to_console("https://ci.example.org/job/Widget/job/Widget/42/")
        == "https://ci.example.org/job/Widget/job/Widget/42/console"
    )


def test_jenkins_job_url_to_console_idempotent() -> None:
    url = "https://ci.example.org/job/Widget/7/console"
    assert jenkins_job_url_to_console(url) == url


def test_jenkins_build_url_from_text_nested_job_path() -> None:
    text = (
        "Patch Set 2: Verified-1\n\nBuild Failed \n\n"
        "https://ci.example.org/job/Widget/job/Widget/99/ : FAILURE"
    )
    assert jenkins_build_url_from_text(text) == "https://ci.example.org/job/Widget/job/Widget/99"


def test_jenkins_build_url_from_text_build_started_inline() -> None:
    text = "Patch Set 1:\n\nBuild Started https://ci.example.org/job/Widget/job/Widget/12/"
    assert jenkins_build_url_from_text(text) == "https://ci.example.org/job/Widget/job/Widget/12"


@pytest.mark.parametrize(
    ("message", "kind", "patch_set", "build_url"),
    [
        (
            "Uploaded patch set 1.",
            "patch_set_upload",
            1,
            None,
        ),
        (
            "Uploaded patch set 3: Patch Set 2 was rebased.",
            "patch_set_upload",
            3,
            None,
        ),
        (
            "Patch Set 1:\n\nBuild Started https://ci.example.org/job/Widget/job/Widget/12/",
            "build_started",
            1,
            "https://ci.example.org/job/Widget/job/Widget/12",
        ),
        (
            "Patch Set 2: Verified-1\n\nBuild Failed \n\n"
            "https://ci.example.org/job/Widget/job/Widget/55/ : FAILURE",
            "build_failed",
            2,
            "https://ci.example.org/job/Widget/job/Widget/55",
        ),
        (
            "Patch Set 4:\n\nNo Builds Executed",
            "no_builds",
            4,
            None,
        ),
    ],
)
def test_parse_change_message_kinds(
    message: str,
    kind: str,
    patch_set: int,
    build_url: str | None,
) -> None:
    parsed = parse_change_message(
        {
            "tag": "autogenerated:jenkins-gerrit-trigger",
            "message": message,
            "_revision_number": patch_set,
        }
    )
    assert parsed.kind == kind
    assert parsed.patch_set == patch_set
    assert parsed.build_url == build_url


def test_default_extract_ci_links_from_build_failed_message() -> None:
    messages = [
        {
            "message": "Patch Set 1:\n\nBuild Started https://ci.example.org/job/Widget/job/Widget/12/",
            "_revision_number": 1,
            "date": "2026-01-01 10:00:00",
        },
        {
            "message": (
                "Patch Set 1: Verified-1\n\nBuild Failed \n\n"
                "https://ci.example.org/job/Widget/job/Widget/12/ : FAILURE"
            ),
            "_revision_number": 1,
            "date": "2026-01-01 10:01:00",
        },
    ]
    links = default_extract_ci_links(project="acme/widget", checks=[], messages=messages)
    assert links == [
        CiLink(
            label="jenkins",
            url="https://ci.example.org/job/Widget/job/Widget/12/console",
            source="message",
        )
    ]


def test_default_extract_ci_links_prefers_latest_failed_patch_set() -> None:
    messages = [
        {
            "message": (
                "Patch Set 1: Verified-1\n\nBuild Failed \n\n"
                "https://ci.example.org/job/Widget/job/Widget/10/ : FAILURE"
            ),
            "_revision_number": 1,
            "date": "2026-01-01 10:00:00",
        },
        {
            "message": (
                "Patch Set 3: Verified-1\n\nBuild Failed \n\n"
                "https://ci.example.org/job/Widget/job/Widget/30/ : FAILURE"
            ),
            "_revision_number": 3,
            "date": "2026-01-02 10:00:00",
        },
    ]
    links = default_extract_ci_links(project="acme/widget", checks=[], messages=messages)
    assert links[0].url == "https://ci.example.org/job/Widget/job/Widget/30/console"


def test_default_extract_ci_links_checks_before_messages() -> None:
    checks = [
        {
            "state": "FAILED",
            "checker_name": "verify",
            "url": "https://ci.example.org/job/Widget/job/Widget/77/",
        }
    ]
    messages = [
        {
            "message": (
                "Patch Set 1: Verified-1\n\nBuild Failed \n\n"
                "https://ci.example.org/job/Widget/job/Widget/12/ : FAILURE"
            ),
            "_revision_number": 1,
        }
    ]
    links = apply_ci_strategy(
        default_extract_ci_links,
        project="acme/widget",
        checks=checks,
        messages=messages,
    )
    assert links == [
        CiLink(
            label="verify",
            url="https://ci.example.org/job/Widget/job/Widget/77/console",
            source="checks",
        )
    ]


def test_extract_ci_links_via_registry_builtin_without_local_registry(stack_repo: Path) -> None:
    clear_ci_strategy_cache()
    messages = [
        {
            "message": (
                "Patch Set 1: Verified-1\n\nBuild Failed \n\n"
                "https://ci.example.org/job/Widget/job/Widget/88/ : FAILURE"
            ),
            "_revision_number": 1,
        }
    ]
    links = extract_ci_links_via_registry(
        stack_repo,
        project="testproj",
        checks=[],
        messages=messages,
    )
    assert links == [
        CiLink(
            label="jenkins",
            url="https://ci.example.org/job/Widget/job/Widget/88/console",
            source="message",
        )
    ]


def test_service_uses_builtin_message_parser_without_registry(stack_repo: Path) -> None:
    clear_ci_strategy_cache()
    rows = stack_rows_mb_to_head(stack_repo)
    details = build_details_by_change_id(rows, per_index_overrides=[{"verified": -1}] * len(rows))
    first_cid = rows[0].change_id
    assert first_cid
    triplet = f"testproj~main~{first_cid}"
    store = ChangeStore(
        details,
        web_base="https://g.example",
        checks={triplet: []},
        messages={
            triplet: [
                {
                    "message": (
                        "Patch Set 1: Verified-1\n\nBuild Failed \n\n"
                        "https://ci.example.org/job/Widget/job/Widget/201/ : FAILURE"
                    ),
                    "_revision_number": 1,
                }
            ]
        },
    )
    service = GerritService.from_cwd(stack_repo, rest=store)
    inputs = [
        CommitStatusInput(
            sha=row.sha,
            short_sha=row.short_sha,
            summary=row.subject,
            change_id=row.change_id,
        )
        for row in rows
    ]
    result = service.fetch_gerrit_data(inputs, cwd=stack_repo)
    matched = next(c for c in result if c.change_id == first_cid)
    assert matched.ci_links == [
        CiLink(
            label="jenkins",
            url="https://ci.example.org/job/Widget/job/Widget/201/console",
            source="message",
        )
    ]
    assert store.calls_to("get_messages")
