"""Tests for Gerrit change message parsing helpers."""

from __future__ import annotations

import pytest

from gerrit_workflow_tools.core.ci_links import CiLink, apply_ci_strategy
from gerrit_workflow_tools.core.ci_strategy import default_extract_ci_links
from gerrit_workflow_tools.core.gerrit_message_parsing import (
    ci_links_from_build_failed_messages,
    ci_pipelines_from_build_messages,
    jenkins_build_url_from_text,
    jenkins_job_url_to_console,
    parse_change_message,
)


def test_jenkins_job_url_to_console_appends_console() -> None:
    assert (
        jenkins_job_url_to_console("https://ci.example.org/job/Widget/job/Widget/42/")
        == "https://ci.example.org/job/Widget/job/Widget/42/console"
    )


def test_jenkins_job_url_to_console_idempotent() -> None:
    url = "https://ci.example.org/job/Widget/7/console"
    assert jenkins_job_url_to_console(url) == url


def test_jenkins_build_url_from_text_nested_job_path() -> None:
    text = "Patch Set 2: Verified-1\n\nBuild Failed \n\nhttps://ci.example.org/job/Widget/job/Widget/99/ : FAILURE"
    assert jenkins_build_url_from_text(text) == "https://ci.example.org/job/Widget/job/Widget/99"


def test_jenkins_build_url_from_text_build_started_inline() -> None:
    text = "Patch Set 1:\n\nBuild Started https://ci.example.org/job/Widget/job/Widget/12/"
    assert jenkins_build_url_from_text(text) == "https://ci.example.org/job/Widget/job/Widget/12"


@pytest.mark.parametrize(
    ("message", "kind", "patch_set", "build_url"),
    [
        (
            "Uploaded patch set 1.",
            "patch_set_upload",
            1,
            None,
        ),
        (
            "Uploaded patch set 3: Patch Set 2 was rebased.",
            "patch_set_upload",
            3,
            None,
        ),
        (
            "Patch Set 1:\n\nBuild Started https://ci.example.org/job/Widget/job/Widget/12/",
            "build_started",
            1,
            "https://ci.example.org/job/Widget/job/Widget/12",
        ),
        (
            "Patch Set 2: Verified-1\n\nBuild Failed \n\nhttps://ci.example.org/job/Widget/job/Widget/55/ : FAILURE",
            "build_failed",
            2,
            "https://ci.example.org/job/Widget/job/Widget/55",
        ),
        (
            "Patch Set 4:\n\nNo Builds Executed",
            "no_builds",
            4,
            None,
        ),
    ],
)
def test_parse_change_message_kinds(
    message: str,
    kind: str,
    patch_set: int,
    build_url: str | None,
) -> None:
    parsed = parse_change_message(
        {
            "tag": "autogenerated:jenkins-gerrit-trigger",
            "message": message,
            "_revision_number": patch_set,
        }
    )
    assert parsed.kind == kind
    assert parsed.patch_set == patch_set
    assert parsed.build_url == build_url


def test_default_extract_ci_links_from_build_failed_message() -> None:
    messages = [
        {
            "message": "Patch Set 1:\n\nBuild Started https://ci.example.org/job/Widget/job/Widget/12/",
            "_revision_number": 1,
            "date": "2026-01-01 10:00:00",
        },
        {
            "message": (
                "Patch Set 1: Verified-1\n\nBuild Failed \n\nhttps://ci.example.org/job/Widget/job/Widget/12/ : FAILURE"
            ),
            "_revision_number": 1,
            "date": "2026-01-01 10:01:00",
        },
    ]
    links = default_extract_ci_links(project="acme/widget", checks=[], messages=messages)
    assert links == [
        CiLink(
            label="jenkins",
            url="https://ci.example.org/job/Widget/job/Widget/12/console",
            source="message",
        )
    ]


def test_default_extract_ci_links_prefers_latest_failed_patch_set() -> None:
    messages = [
        {
            "message": (
                "Patch Set 1: Verified-1\n\nBuild Failed \n\nhttps://ci.example.org/job/Widget/job/Widget/10/ : FAILURE"
            ),
            "_revision_number": 1,
            "date": "2026-01-01 10:00:00",
        },
        {
            "message": (
                "Patch Set 3: Verified-1\n\nBuild Failed \n\nhttps://ci.example.org/job/Widget/job/Widget/30/ : FAILURE"
            ),
            "_revision_number": 3,
            "date": "2026-01-02 10:00:00",
        },
    ]
    links = default_extract_ci_links(
        project="acme/widget",
        checks=[],
        messages=messages,
        current_revision_number=3,
    )
    assert links[0].url == "https://ci.example.org/job/Widget/job/Widget/30/console"


def test_ci_links_from_build_failed_messages_filters_to_current_revision() -> None:
    messages = [
        {
            "message": (
                "Patch Set 1: Verified-1\n\nBuild Failed \n\nhttps://ci.example.org/job/Widget/job/Widget/10/ : FAILURE"
            ),
            "_revision_number": 1,
            "date": "2026-01-01 10:00:00",
        },
        {
            "message": (
                "Patch Set 3: Verified-1\n\nBuild Failed \n\nhttps://ci.example.org/job/Widget/job/Widget/30/ : FAILURE"
            ),
            "_revision_number": 3,
            "date": "2026-01-02 10:00:00",
        },
    ]
    links = ci_links_from_build_failed_messages(messages, current_revision_number=1)
    assert len(links) == 1
    assert links[0].url == "https://ci.example.org/job/Widget/job/Widget/10/console"


def test_ci_pipelines_from_build_messages_current_revision_only() -> None:
    messages = [
        {
            "message": "Patch Set 3:\n\nBuild Started https://ci.example.org/job/Widget/job/Widget/30/",
            "_revision_number": 3,
            "date": "2026-01-02 10:00:00",
        },
        {
            "message": (
                "Patch Set 1: Verified-1\n\nBuild Failed \n\nhttps://ci.example.org/job/Widget/job/Widget/10/ : FAILURE"
            ),
            "_revision_number": 1,
            "date": "2026-01-01 10:00:00",
        },
    ]
    pipelines = ci_pipelines_from_build_messages(messages, current_revision_number=3)
    assert len(pipelines) == 1
    assert pipelines[0].state == "IN_PROGRESS"
    assert pipelines[0].outdated is False


def test_ci_pipelines_from_build_messages_outdated_fallback() -> None:
    messages = [
        {
            "message": (
                "Patch Set 1: Verified-1\n\nBuild Failed \n\nhttps://ci.example.org/job/Widget/job/Widget/10/ : FAILURE"
            ),
            "_revision_number": 1,
            "date": "2026-01-01 10:00:00",
        },
    ]
    pipelines = ci_pipelines_from_build_messages(
        messages,
        current_revision_number=3,
        include_outdated_fallback=True,
    )
    assert len(pipelines) == 1
    assert pipelines[0].state == "FAILED"
    assert pipelines[0].outdated is True


def test_default_extract_ci_links_checks_before_messages() -> None:
    checks = [
        {
            "state": "FAILED",
            "checker_name": "verify",
            "url": "https://ci.example.org/job/Widget/job/Widget/77/",
        }
    ]
    messages = [
        {
            "message": (
                "Patch Set 1: Verified-1\n\nBuild Failed \n\nhttps://ci.example.org/job/Widget/job/Widget/12/ : FAILURE"
            ),
            "_revision_number": 1,
        }
    ]
    links = apply_ci_strategy(
        default_extract_ci_links,
        project="acme/widget",
        checks=checks,
        messages=messages,
    )
    assert links == [
        CiLink(
            label="verify",
            url="https://ci.example.org/job/Widget/job/Widget/77/console",
            source="checks",
        )
    ]
