"""Parse Gerrit change messages and extract CI URLs.

Built-in parsers recognise Jenkins Gerrit trigger messages (``Build Started``,
``Build Failed``, ``No Builds Executed``) and Gerrit patch-set upload lines.
Custom parsers can be registered via ``.ger/ci/registry.py`` — see
``docu/gerrit-ci-strategies.md``.
"""

from __future__ import annotations

import re
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Any, Literal

from gerrit_workflow_tools.core.ci_links import CiLink, CiPipeline


GerritMessageKind = Literal[
    "patch_set_upload",
    "build_started",
    "build_failed",
    "no_builds",
    "unknown",
]

# Jenkins job build URL (supports nested ``/job/…/job/…/<n>/`` paths).
_JENKINS_BUILD_URL_RE = re.compile(
    r"(https?://\S+?/job/(?:\S+?/)+\d+)/?(?:\s*:\s*FAILURE)?",
    re.IGNORECASE,
)
_BUILD_FAILED_RE = re.compile(r"Build\s+Failed", re.IGNORECASE)
_BUILD_STARTED_RE = re.compile(r"Build\s+Started", re.IGNORECASE)
_NO_BUILDS_RE = re.compile(r"No\s+Builds\s+Executed", re.IGNORECASE)
_UPLOADED_PS_RE = re.compile(r"Uploaded\s+patch\s+set\s+(\d+)", re.IGNORECASE)
_PATCH_SET_HEADER_RE = re.compile(
    r"Patch\s+Set\s+(\d+)(?::\s*(\S+))?",
    re.IGNORECASE,
)


@dataclass(frozen=True)
class GerritMessageParseResult:
    """Structured view of one change message body."""

    kind: GerritMessageKind
    patch_set: int | None = None
    build_url: str | None = None
    label_vote: str | None = None


def jenkins_job_url_to_console(url: str) -> str:
    """Rewrite a Jenkins job build URL to its console page."""

    base = url.rstrip("/")
    if "/console" in base:
        return base
    return f"{base}/console"


def jenkins_build_url_from_text(text: str) -> str | None:
    """Return the first Jenkins build URL embedded in *text*, if any."""

    match = _JENKINS_BUILD_URL_RE.search(text)
    if not match:
        return None
    return match.group(1).rstrip("/")


def parse_change_message(msg: Mapping[str, Any]) -> GerritMessageParseResult:
    """Classify a Gerrit ChangeMessageInfo row and extract useful fields."""

    text = str(msg.get("message") or "")
    tag = str(msg.get("tag") or "")

    upload = _UPLOADED_PS_RE.search(text)
    if upload or tag == "autogenerated:gerrit:newPatchSet":
        ps = int(upload.group(1)) if upload else _revision_number(msg)
        return GerritMessageParseResult(kind="patch_set_upload", patch_set=ps)

    header = _PATCH_SET_HEADER_RE.match(text)
    patch_set = int(header.group(1)) if header else _revision_number(msg)
    label_vote = header.group(2) if header and header.group(2) else None

    if _BUILD_FAILED_RE.search(text):
        return GerritMessageParseResult(
            kind="build_failed",
            patch_set=patch_set,
            build_url=jenkins_build_url_from_text(text),
            label_vote=label_vote,
        )
    if _BUILD_STARTED_RE.search(text):
        return GerritMessageParseResult(
            kind="build_started",
            patch_set=patch_set,
            build_url=jenkins_build_url_from_text(text),
            label_vote=label_vote,
        )
    if _NO_BUILDS_RE.search(text):
        return GerritMessageParseResult(kind="no_builds", patch_set=patch_set)

    return GerritMessageParseResult(kind="unknown", patch_set=patch_set)


def _revision_number(msg: Mapping[str, Any]) -> int | None:
    raw = msg.get("_revision_number")
    return raw if isinstance(raw, int) else None


def _message_revision(msg: Mapping[str, Any], parsed: GerritMessageParseResult) -> int | None:
    return parsed.patch_set if parsed.patch_set is not None else _revision_number(msg)


def _message_sort_key(msg: Mapping[str, Any]) -> tuple[int, str]:
    rev = _revision_number(msg)
    date = str(msg.get("date") or "")
    return (rev if rev is not None else -1, date)


def ci_links_from_failed_checks(checks: Sequence[Mapping[str, Any]]) -> list[CiLink]:
    """Turn failed Checks-plugin rows into console deep links."""

    out: list[CiLink] = []
    for row in checks:
        if row.get("state") != "FAILED":
            continue
        raw = row.get("url") or row.get("external_id") or ""
        if not isinstance(raw, str) or not raw.startswith("http"):
            continue
        name = row.get("checker_name") or row.get("name") or "jenkins"
        out.append(
            CiLink(
                label=str(name),
                url=jenkins_job_url_to_console(raw),
                source="checks",
            )
        )
    return out


def ci_links_from_build_failed_messages(
    messages: Sequence[Mapping[str, Any]],
    *,
    current_revision_number: int | None = None,
) -> list[CiLink]:
    """Extract Jenkins console links from ``Build Failed`` change messages."""

    candidates: list[tuple[tuple[int, str], CiLink]] = []
    for msg in messages:
        parsed = parse_change_message(msg)
        if parsed.kind != "build_failed" or not parsed.build_url:
            continue
        rev = _message_revision(msg, parsed)
        if current_revision_number is not None and rev != current_revision_number:
            continue
        candidates.append(
            (
                _message_sort_key(msg),
                CiLink(
                    label="jenkins",
                    url=jenkins_job_url_to_console(parsed.build_url),
                    source="message",
                ),
            )
        )
    if not candidates:
        return []
    candidates.sort(key=lambda item: item[0])
    return [candidates[-1][1]]


def _build_message_state(parsed: GerritMessageParseResult) -> str:
    if parsed.kind == "build_failed":
        return "FAILED"
    if parsed.kind == "build_started":
        vote = (parsed.label_vote or "").lower()
        if vote == "verified+1":
            return "SUCCESSFUL"
        return "IN_PROGRESS"
    return ""


def _dedupe_pipelines_latest(items: list[tuple[tuple[int, str], CiPipeline]]) -> list[CiPipeline]:
    """Keep the latest message per URL."""

    by_url: dict[str | None, tuple[tuple[int, str], CiPipeline]] = {}
    for sort_key, pipeline in items:
        key = pipeline.url
        if key not in by_url or sort_key > by_url[key][0]:
            by_url[key] = (sort_key, pipeline)
    ordered = sorted(by_url.values(), key=lambda item: item[0])
    return [pipeline for _, pipeline in ordered]


def ci_pipelines_from_build_messages(
    messages: Sequence[Mapping[str, Any]],
    *,
    current_revision_number: int | None,
    include_outdated_fallback: bool = False,
) -> list[CiPipeline]:
    """Build CI pipelines from Jenkins build messages, scoped to the current patch set."""

    items: list[tuple[tuple[int, str], int | None, CiPipeline]] = []
    for msg in messages:
        parsed = parse_change_message(msg)
        if parsed.kind not in ("build_failed", "build_started") or not parsed.build_url:
            continue
        rev = _message_revision(msg, parsed)
        state = _build_message_state(parsed)
        if not state:
            continue
        outdated = current_revision_number is not None and rev is not None and rev < current_revision_number
        items.append(
            (
                _message_sort_key(msg),
                rev,
                CiPipeline(
                    label="jenkins",
                    state=state,
                    url=jenkins_job_url_to_console(parsed.build_url),
                    outdated=outdated,
                ),
            )
        )
    if not items:
        return []

    if current_revision_number is not None:
        current_items = [(sort_key, pipeline) for sort_key, rev, pipeline in items if rev == current_revision_number]
        if current_items:
            return _dedupe_pipelines_latest(current_items)
        if include_outdated_fallback:
            revs = [rev for _, rev, _ in items if rev is not None]
            if not revs:
                return []
            latest_rev = max(revs)
            fallback_items = [
                (
                    sort_key,
                    CiPipeline(
                        label=pipeline.label,
                        state=pipeline.state,
                        url=pipeline.url,
                        outdated=True,
                    ),
                )
                for sort_key, rev, pipeline in items
                if rev == latest_rev
            ]
            return _dedupe_pipelines_latest(fallback_items)

    return _dedupe_pipelines_latest([(sort_key, pipeline) for sort_key, _, pipeline in items])


__all__ = [
    "GerritMessageKind",
    "GerritMessageParseResult",
    "ci_links_from_build_failed_messages",
    "ci_links_from_failed_checks",
    "ci_pipelines_from_build_messages",
    "jenkins_build_url_from_text",
    "jenkins_job_url_to_console",
    "parse_change_message",
]
