"""Parse Gerrit change messages and extract CI URLs.

Built-in parsers recognise Jenkins Gerrit trigger messages (``Build Started``,
``Build Failed``, ``No Builds Executed``) and Gerrit patch-set upload lines.
Custom parsers can be registered via ``.ger/ci/registry.py`` — see
``docu/gerrit-ci-strategies.md``.
"""

from __future__ import annotations

import re
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Any, Literal

from gerrit_workflow_tools.core.ci_links import CiLink

GerritMessageKind = Literal[
    "patch_set_upload",
    "build_started",
    "build_failed",
    "no_builds",
    "unknown",
]

# Jenkins job build URL (supports nested ``/job/…/job/…/<n>/`` paths).
_JENKINS_BUILD_URL_RE = re.compile(
    r"(https?://\S+?/job/(?:\S+?/)+\d+)/?(?:\s*:\s*FAILURE)?",
    re.IGNORECASE,
)
_BUILD_FAILED_RE = re.compile(r"Build\s+Failed", re.IGNORECASE)
_BUILD_STARTED_RE = re.compile(r"Build\s+Started", re.IGNORECASE)
_NO_BUILDS_RE = re.compile(r"No\s+Builds\s+Executed", re.IGNORECASE)
_UPLOADED_PS_RE = re.compile(r"Uploaded\s+patch\s+set\s+(\d+)", re.IGNORECASE)
_PATCH_SET_HEADER_RE = re.compile(
    r"Patch\s+Set\s+(\d+)(?::\s*(\S+))?",
    re.IGNORECASE,
)


@dataclass(frozen=True)
class GerritMessageParseResult:
    """Structured view of one change message body."""

    kind: GerritMessageKind
    patch_set: int | None = None
    build_url: str | None = None
    label_vote: str | None = None


def jenkins_job_url_to_console(url: str) -> str:
    """Rewrite a Jenkins job build URL to its console page."""

    base = url.rstrip("/")
    if "/console" in base:
        return base
    return f"{base}/console"


def jenkins_build_url_from_text(text: str) -> str | None:
    """Return the first Jenkins build URL embedded in *text*, if any."""

    match = _JENKINS_BUILD_URL_RE.search(text)
    if not match:
        return None
    return match.group(1).rstrip("/")


def parse_change_message(msg: Mapping[str, Any]) -> GerritMessageParseResult:
    """Classify a Gerrit ChangeMessageInfo row and extract useful fields."""

    text = str(msg.get("message") or "")
    tag = str(msg.get("tag") or "")

    upload = _UPLOADED_PS_RE.search(text)
    if upload or tag == "autogenerated:gerrit:newPatchSet":
        ps = int(upload.group(1)) if upload else _revision_number(msg)
        return GerritMessageParseResult(kind="patch_set_upload", patch_set=ps)

    header = _PATCH_SET_HEADER_RE.match(text)
    patch_set = int(header.group(1)) if header else _revision_number(msg)
    label_vote = header.group(2) if header and header.group(2) else None

    if _BUILD_FAILED_RE.search(text):
        return GerritMessageParseResult(
            kind="build_failed",
            patch_set=patch_set,
            build_url=jenkins_build_url_from_text(text),
            label_vote=label_vote,
        )
    if _BUILD_STARTED_RE.search(text):
        return GerritMessageParseResult(
            kind="build_started",
            patch_set=patch_set,
            build_url=jenkins_build_url_from_text(text),
            label_vote=label_vote,
        )
    if _NO_BUILDS_RE.search(text):
        return GerritMessageParseResult(kind="no_builds", patch_set=patch_set)

    return GerritMessageParseResult(kind="unknown", patch_set=patch_set)


def _revision_number(msg: Mapping[str, Any]) -> int | None:
    raw = msg.get("_revision_number")
    return raw if isinstance(raw, int) else None


def _message_sort_key(msg: Mapping[str, Any]) -> tuple[int, str]:
    rev = _revision_number(msg)
    date = str(msg.get("date") or "")
    return (rev if rev is not None else -1, date)


def ci_links_from_failed_checks(checks: Sequence[Mapping[str, Any]]) -> list[CiLink]:
    """Turn failed Checks-plugin rows into console deep links."""

    out: list[CiLink] = []
    for row in checks:
        if row.get("state") != "FAILED":
            continue
        raw = row.get("url") or row.get("external_id") or ""
        if not isinstance(raw, str) or not raw.startswith("http"):
            continue
        name = row.get("checker_name") or row.get("name") or "jenkins"
        out.append(
            CiLink(
                label=str(name),
                url=jenkins_job_url_to_console(raw),
                source="checks",
            )
        )
    return out


def ci_links_from_build_failed_messages(messages: Sequence[Mapping[str, Any]]) -> list[CiLink]:
    """Extract Jenkins console links from ``Build Failed`` change messages."""

    candidates: list[tuple[tuple[int, str], CiLink]] = []
    for msg in messages:
        parsed = parse_change_message(msg)
        if parsed.kind != "build_failed" or not parsed.build_url:
            continue
        candidates.append(
            (
                _message_sort_key(msg),
                CiLink(
                    label="jenkins",
                    url=jenkins_job_url_to_console(parsed.build_url),
                    source="message",
                ),
            )
        )
    if not candidates:
        return []
    candidates.sort(key=lambda item: item[0])
    return [candidates[-1][1]]


def builtin_extract_ci_links(
    *,
    project: str,
    checks: list[dict[str, Any]],
    messages: list[dict[str, Any]],
) -> list[CiLink]:
    """Default CI strategy: Checks rows first, then Jenkins ``Build Failed`` messages."""

    del project  # built-in applies to every project
    from_checks = ci_links_from_failed_checks(checks)
    if from_checks:
        # LazyRows gate: do not iterate messages (and trigger get_messages) when checks answer.
        return from_checks
    return ci_links_from_build_failed_messages(messages)


__all__ = [
    "GerritMessageKind",
    "GerritMessageParseResult",
    "builtin_extract_ci_links",
    "ci_links_from_build_failed_messages",
    "ci_links_from_failed_checks",
    "jenkins_build_url_from_text",
    "jenkins_job_url_to_console",
    "parse_change_message",
]
